language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0-p195

gemfile:
  - ./gemfiles/Gemfile.chef.0.10.10
  - ./gemfiles/Gemfile.chef.10.12.0
  - ./gemfiles/Gemfile.chef.10.14.0
  - ./gemfiles/Gemfile.chef.10.16.0
  - ./gemfiles/Gemfile.chef.11.4.4
